name: uctflutter
description: A new Flutter project.

dependencies:
  fixnum: ^0.10.5
  protobuf: ^0.10.2
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  scoped_model: ^0.3.0
  sqflite: any
  path_provider: any
  collection: ^1.14.11
  flutter_slidable: ^0.4.6
  tuple: ^1.0.2
  flutter_local_notifications: ^0.4.4+2
  firebase_analytics: ^1.1.0
  firebase_messaging: ^2.1.0
  firebase_performance: ^0.0.8+1
  http: ^0.12.0+1
  flutter_simple_dependency_injection: any
  package_info: ^0.3.2+1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

dependency_overrides:
  logging: ^0.11.3+2


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # fonts:

  assets:
  - res/images/board.webp

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies, 
  # see https://flutter.io/custom-fonts/#from-packages
